### ISSUE TITLE
[QUESTION] About the Export function

### ISSUE THREAD

**Issue by chrisvidal** [mplodowski/formbuilder-plugin-public#14]
Does the export function export the form data as `one field per column`, or `all for data in one column with a separator`?

**Comment by mplodowski** [comment]
This is example export file.

[export_log.csv](https://github.com/mplodowski/formbuilder-plugin-public/files/8303509/export_log.csv)

**Comment by chrisvidal** [comment]
thanks appreciate it. 
So, the form data are exported as a String of Json data in one column.
