### ISSUE TITLE
File Upload - Required

### ISSUE THREAD

**Issue by afdstudio** [mplodowski/formbuilder-plugin-public#16]
**Describe the bug**
I created a form with field "file uploader". I want it to be mandatory.
So, in validation I put "required".
However, this is not working as the system doesn't recognize the attached file.
Did I need to introduce another way of validation? Can you give me some help on this?
Thank you in advance!

**To Reproduce**
1. Go to '[link here](https://www.avminho.com/faturas)'
2. Try to attach a file
3. Submit form

**Expected behavior**
File uploader should be mandatory.

**Screenshots**
<img width="683" alt="Captura de ecrã 2022-04-04, às 19 36 28" src="https://user-images.githubusercontent.com/18419250/161610176-c61b6757-1456-4742-adc3-cf9f67d5b1ce.png">

**October version**
2.2.15

**Plugin version**
2.1.6

**Additional context**

**Comment by bojko91** [comment]
Same here, did you find solution?

**Comment by mplodowski** [comment]
Form Builder plugin uses Responsiv.Uploader plugin to manage file uploads. Currently there is no option to make files as required. I will try to look into this more, but for now I don't have solution.
