### ISSUE TITLE
Class October\Rain\Support\Facades\Schema Not Found OctoberCMS v3.0.16

### ISSUE THREAD

**Issue by Anrecky** [mplodowski/formbuilder-plugin-public#18]
According [version history](https://docs.octobercms.com/2.x/plugin/updates.html#plugin-version-file) OctoberCMS v3.0.16 for the Class October\Rain\Support\Facades\Schema is just Class Schema.

So it works fine when i change 
use October\Rain\Support\Facades\Schema; 
to
use Schema;

**Comment by mplodowski** [comment]
Fixed in version 2.1.7.
