### ISSUE TITLE
Using static pages variable field for selecting a form

### ISSUE THREAD

**Issue by kevin-invato** [mplodowski/formbuilder-plugin-public#19]
Hi there,

My client is working with a lot of different forms and wishes to choose which form renders on a page. 

For managing pages and content, we use Static Pages, and I made a custom field ("use_form") in a layout file. But there is an issue when I load the RenderForm component with that dynamic value. I always get the error:

'Form with code "(my chosen form)" does not exist! Did you select correct form in component settings?' 

I tried using the snippets, that works fine, but it only shows the default component markup, not the overrided component markup in my theme.

So my question is: is there a way to select a form dynamically with static pages?

Thanks in advance!

**Comment by spacebeers** [comment]
On a site using Builder plugin I had to manually add each form to the template as components and then have a big switch statement. The page fields contain a drop down with form ID's in which seems to work for me but I'm sure it could be done more nicely.
