### ISSUE TITLE
Error Sending Form After Updating to 2.1.0

### ISSUE THREAD

**Issue by kombimedia** [mplodowski/formbuilder-plugin-public#2]
**Describe the bug**
I have updated to the latest version of the plugin 2.1.0 and run the database patch. Now when a form is submitted an alert window pops up with a 'something went wrong' message.

**To Reproduce**
1. Go to a form on the front end
2. Complete the form fields
3. Click submit
4. Alert message pops up with 'something went wrong' alert message

**Expected behavior**
I expected the form to submit

**Screenshots**
![Screen Shot 2021-11-22 at 15 24 29](https://user-images.githubusercontent.com/28551935/142794794-ad3dd8a5-47c1-40da-9522-260970f1bb54.png)

![Screen Shot 2021-11-22 at 15 40 38](https://user-images.githubusercontent.com/28551935/142793439-ca909116-2eb4-4414-b8ee-52c5d4bb6bd2.png)

**October version**
2.1.21

**Plugin version**
2.1.0

**Additional Details**
I am extending the FormBuilder plugin to dynamically set the recipient name and email before the message is sent.
```
     public function boot() {
      \Event::listen('formBuilder.beforeSendMessage', function ($form, $data) {
        $form->to_email = $data['recipient_email'];
        $form->to_name = $data['recipient_name'];

      });
```

Hope you can help.

Cy

**Comment by mplodowski** [comment]
Please go to the backend Settings -> Event Log. There should be error record. Copy and paste error message and stack trace.

In new version `to_email` and `to_name` field are replaced with repeater `recipients`  field.

I think you can remove this boot method and use Autoresponder feature, where you can specify which fields to use and even the mail template.

**Comment by mplodowski** [comment]
If you want to use `boot` method to change recipients than this is the code to use now:

```
\Event::listen('formBuilder.beforeSendMessage', function ($form, $data) {
    $form->recipients = [
        [
            'email' => $data['recipient_email'],
            'recipient_name' => $data['recipient_name'],
        ]
    ];
});
```

**Comment by kombimedia** [comment]
Hi @mplodowski,

Thanks for your speedy response.

There was no event logged for this error.

Thanks also for the updated `boot` method snippet. Because the email recipient will always need to be dynamically injected I have gone for this method to override the default recipient, preventing two emails being sent.

Cheers

**Comment by mplodowski** [comment]
Without seeing error message there is very limited way to help you.

The only way to see this error is to enable APP_DEBUG = true in .env file.

You can also run: `composer update` in project root.

The last resort should be reinstalling plugin, but can cause data loss.

**Comment by kombimedia** [comment]
@mplodowski, 

Sorry, I wasn't clear. I'm not receiving the error anymore. I have updated my `boot` method to the one you provided, and removed un-required recipient repeaters that had been generated after upgrading to 2.1.0. I think the error i was receiving was due to a 'new recipient' not having an email address defined.

Thanks

**Comment by mplodowski** [comment]
Super! I am glad it works now.
