### ISSUE TITLE
Support October v3 BETA

### ISSUE THREAD

**Issue by cloudwales** [mplodowski/formbuilder-plugin-public#20]
**Describe the bug**
Have an issue with sending a message. Created a webform and when I submit in the frontend it displays a popup saying `There was an error. Please try again!`.
If I select no template it works but then you don't get any information through.

**Screenshots**

**October version**
3.0.23

**Plugin version**
2.1.7

Looking in the error logs theres nothing. Only under the browsers inspection console I get error 500 with the jquery file. Jquery loaded correctly and also framework tags and scripts. Under Form Logs, there is no subject, sender etc but when you click into it you can see under Form Data that there is data passed through.

**Comment by mplodowski** [comment]
Hi,

currently October v3 is in beta state. I pushed new branch (dev-develop), where I will push updates for this version, until October v3 is marked as stable.

To use this branch, you must update your composer.json file.

Before:
`"renatio/formbuilder-plugin": "^2.1"`

After:
`"renatio/formbuilder-plugin": "dev-develop"`

Let me know if this fix your issue.

**Comment by mplodowski** [comment]
Version 3.1.0 have full support for October CMS 3.0+
