### ISSUE TITLE
Duplicate form with no field types

### ISSUE THREAD

**Issue by slaik** [mplodowski/formbuilder-plugin-public#25]
**Describe the bug**
When duplicating a form, its fields are lost

**To Reproduce**
1. Go to 'Forms list'
2. Click on 'Duplicate'
3. Click on new form switch to fields
4. It's emrty

**Expected behavior**
In duplicate action after a replicating the form you get fields from replicated form. But you should get fields from original form

**Fix**
In actions/DuplicateForm.php change row 24 from:
foreach ($copy->fields as $field) {
to:
foreach ($this->form->fields as $field) {

**October version**
2.2.27

**Plugin version**
2.2.0

**Additional context**

![Screen Shot 2022-10-13 at 23 22 51](https://user-images.githubusercontent.com/1203924/195664217-1c9eb432-59f8-4129-ba76-73afd2e64447.png)

**Comment by mplodowski** [comment]
Version 3.1.0 have this fixed. Thanks!
