### ISSUE TITLE
A 2nd FormLog is created when SendEmailMessage::sendAutoresponderMessage() is called

### ISSUE THREAD

**Issue by SamZimple** [mplodowski/formbuilder-plugin-public#26]
**Describe the bug**
A 2nd FormLog is created when SendEmailMessage::sendAutoresponderMessage() is called

**To Reproduce**
1. Create a form in the CMS
2. Configure Autoresponder for that form
3. Submit the form on the frontend
4. Check the FormLogs section of the CMS to confirm that 2 Logs were created for a single form submission.

**Expected behavior**
Only 1 FormLog should be created per form submission

**Screenshots**
![Capture](https://user-images.githubusercontent.com/44284080/200474071-68062a46-ffbd-4371-ac9c-a6ed22e4b4a3.PNG)

**October version**
2.2.25

**Plugin version**
2.2.0

**Additional context**
This problem can be fixed by removing line 59 in formbuilder/listeners/SendEmailMessage.php, in the function sendAutoresponderMessage() remove $this->setHeaders($message);

**Comment by mplodowski** [comment]
This is by design, because autoresponder send new mail message with separate recipient and mail template.

In new version I will add a flag so this can be disabled.

**Comment by mplodowski** [comment]
This is available in version 3.1.2.
