### ISSUE TITLE
Form submit 500 error

### ISSUE THREAD

**Issue by spacebeers** [mplodowski/formbuilder-plugin-public#32]
On upgrading to October 2.2.35 and plugin 2.2.0 I cannot send forms. 

Each submission returns a 500 from the server now instead of submitting the form successfully to the user. 

Strangely enough the form _does_ go into the form log but the user never sees the success state. 

**To Reproduce**
1. Go to https://staging.7thsense.one/form-test
2. Fill in the form
3. Submit the form

**October version**
2.2.35

**Plugin version**
2.2.0

**Comment by mplodowski** [comment]
Hi,

sorry for late response. Do you still have the issue?

Regards,
Michal
