### ISSUE TITLE
Use HTML inside label in checkbox

### ISSUE THREAD

**Issue by alendr** [mplodowski/formbuilder-plugin-public#34]
Hello,

Is It possible to create checkbox where you have <a href="#"></a> inside label?

Why? In all form you need to have some kind of before submit button: I agree with Terms&Condition, and then you have like:

I agree with <a target="_blank" href="/terms-and-conditions">Terms&Condition.</a>

Thanks.

**Comment by mplodowski** [comment]
Hi,

in this case I would duplicate checkbox field type to create custom checkbox. Then you can adjust this custom checkbox markup and add anchor tag like so:

```
<div class="{{ wrapper_class }}">
    <div class="form-check">
        <input
            id="{{ name }}"
            name="{{ name }}"
            class="{{ class }} form-check-input"
            value="1"
            type="checkbox"
            {{ default ? 'checked' : '' }}
            {{ custom_attributes|raw }}
        >
        <label for="{{ name }}" class="{{ label_class }} form-check-label">
            {{ label }} <a target="_blank" href="/terms">Terms & Conditions</a>
        </label>

        <div data-validate-for="{{ name }}" class="invalid-feedback"></div>

        {% if comment %}
            <div class="form-text">{{ comment|raw }}</div>
        {% endif %}
    </div>
</div>
```

Now in your form just change field type to your custom checkbox.

**Comment by alendr** [comment]
Hello,

This i need to duplicate inside your plugin folder updates/fileds ? 

Thanks

**Comment by mplodowski** [comment]
No, everything I wrote can be done in the backend area. Go to Form Builder -> Field Types -> Find checkbox field on the list -> Click Duplicate button.
