### ISSUE TITLE
Cannot Access the Backend After Update

### ISSUE THREAD

**Issue by artistro08** [mplodowski/formbuilder-plugin-public#4]
**Describe the bug**
I cannot access the form builder backend. Alternatively I cannot access the pages part of my backend as well. Everything isn't translated and has some remnant translation code displaying on the other parts of the backend. Wherever the component is, it says that some trait is not found

**To Reproduce**
Install Plugin
Try to open the plugin page

**Expected behavior**
Plugin page appears and I can build a form. 
**Screenshots**
![image](https://user-images.githubusercontent.com/6427230/142856987-d668af02-d41e-4a16-9237-2daf6193500c.png)

**October version**
2.1.20

**Plugin version**
2.1.0

**Comment by mplodowski** [comment]
Recently I had similar issue, where I had weird errors. 

The solution was to restart development server.

In my case I am using Laravel Valet, so the solution was to run following command:

`valet restart`

**Comment by artistro08** [comment]
You're a wizard! Thank you!
