### ISSUE TITLE
resetForm function does not fire

### ISSUE THREAD

**Issue by petrsiroky** [mplodowski/formbuilder-plugin-public#42]
**Describe the bug**
Hi, I'm having trouble submitting the form. The form is submitted and displays a success message, but the resetForm function does not fire. Has anyone encountered this problem. Thank you

**Screenshots**
![image](https://github.com/mplodowski/formbuilder-plugin-public/assets/67001291/1131f57e-23d8-4e30-a125-3d748e4dd50e)

**October version**
3.6.3

**Plugin version**
4.0.4

**Comment by mplodowski** [comment]
Check your layout has following code:

```
{% styles %}
{% framework extras %}
{% scripts %}
```

Also check if `form.js?v=4` is loaded in developer toolbar network tab.

Maybe this will help:

https://github.com/mplodowski/formbuilder-plugin-public/issues/5

**Comment by petrsiroky** [comment]
Ah, I already found the problem. I had a script in the `<head>` section. After moving it before the `</body>` tag, everything works. Thank you
