### ISSUE TITLE
Can we support Tailwind?

### ISSUE THREAD

**Issue by fkomaralp** [mplodowski/formbuilder-plugin-public#46]
Hi, I see your plugin is supporting bootstrap 5. We buyed your plugin on octobercms but we cannot apply Tailwind theme. How can we do this?

**Comment by mplodowski** [comment]
Bootstrap is default CSS framework used in plugin, but you can use whatever works for you.

You can override default fields markup or create new fields with tailwind classes. There is a lot of flexibility there, so it should be possible to use tailwindcss with plugin.

Tailwindcss may be supported in the future, but I cannot give you exact time when it will be ready.
