### ISSUE TITLE
could not make your forms plugin for

### ISSUE THREAD

**Issue by sporlab** [mplodowski/formbuilder-plugin-public#49]
Hi

We couldn't make your plugin work on our website https://crossroadscare.space/
My developer explained that your plugin is compatible with Bootstrap 5 but not with Tailwind and therefore we are unable to utilize the plugin although we paid for it.

Thanks 
Tolga
sporlab@gmail.com

**Comment by mplodowski** [comment]
Hi,

sorry to hear that. I think there is some misunderstanding here. 

Plugin is developed to work for October CMS, so it does not depends on CSS framework. Bootstrap is just CSS framework used by default (as in the default October Demo Theme) to style form elements, so it will not look ugly by default. 

You can use any CSS framework you want or just write plain CSS to style it. This depends on your project needs. There are CSS classes on each form element that you can hook Tailwind classes and apply them like so:

```
.form-control {
    @apply bg-gray-300 text-white;
}
```

Plugin helps to create forms, handles form validation, send emails, log form requests, etc. Styling the form is developer task responsible for your project.

I replied your developer here: https://github.com/mplodowski/formbuilder-plugin-public/issues/46

I think you can write to October team and ask for refund.
