### ISSUE TITLE
Add Form Builder to Offline.Box plugin

### ISSUE THREAD

**Issue by Andrea-Tecnotrade** [mplodowski/formbuilder-plugin-public#53]
I created a box in Offline.Box plugin that allow to choose a form from your plugin, but as i send the form it keeps giving me an error:
error 406: "non acceptable".
To make it work on Offline.Box I had to add a render method in your plugin to dinamycally pass the form code, but it looks like that the framework-extra doesn't work properly as i submit the form.

Can you please give me some help.
Thank you verry much
Sincerely
Andrea
andrea@tecnotrade.com

**Comment by mplodowski** [comment]
Hi,

I am not familiar with Offline.Box plugin. Please ask the author of the Offline.Box plugin if what you are doing is possible and can he guide you to accomplish your task. You can write him, that I can make adjustments in my plugin if something is missing to support it.

Regards,
Michal
