### ISSUE TITLE
Error deleting form log

### ISSUE THREAD

**Issue by adrian-stein** [mplodowski/formbuilder-plugin-public#54]
**Describe the bug**
I cant delete form logs as it errors out as below

"Attempt to read property "each" on null" on line 30 of \plugins\renatio\formbuilder\models\FormLog.php

I have upload fields in my form.
 

**To Reproduce**
1. Go to 'Form Logs'
2. Click on '.Select a log..'
3. Scroll down to 'Press delete'
5. See error

**October version**
3.6.0

**Plugin version**
4.0.6

**Comment by SamZimple** [comment]
I have a fix for this error, any chance it could be added to the plugin?
Replace Line 30 of \plugins\renatio\formbuilder\models\FormLog.php
 `$this->{$field->name}->each->delete();`
with
`if(!empty($this->{$field->name}->each)){
                $this->{$field->name}->each->delete();
            }else{
                $this->{$field->name}->delete();
            }`

**Comment by mplodowski** [comment]
Hi

**Comment by adrian-stein** [comment]
HI @mplodowski hopefully you had a good trip. Any word on fixing the bug yet?

**Comment by mplodowski** [comment]
Hi, sorry for delay. 

I had some issues to reproduce bug with default form. Finally I changed upload field to not use multiple files and it was triggered.

It should be fixed in version 4.0.7. Please update plugin and let me know if it works for you.

Thank you for your patience.

**Comment by SamZimple** [comment]
Thank @mplodowski that works
