### ISSUE TITLE
Access to the required property

### ISSUE THREAD

**Issue by envas** [mplodowski/formbuilder-plugin-public#55]
I am using Tailwind and I would like to visually style all required fields in the field wrapper class. Is there a way how to access the validation rules in the twig code? Example with a variable `is_required`

```
<div class="{{ wrapper_class }} {{ is_required ? 'required }}">
```

**Comment by mplodowski** [comment]
Hi,

you can access `field.validation` and check if this string contains 'required' string to accomplish what you need.

You can alse use custom attributes and add `required` attribute to field. Then use `:invalid` state to style input with Tailwind like so:

`invalid:border-red-500 invalid:text-red-600 focus:invalid:border-red-500 focus:invalid:ring-red-500`
