### ISSUE TITLE
Update breaks everything

### ISSUE THREAD

**Issue by der-On** [mplodowski/formbuilder-plugin-public#6]
After an update to version 2.1.0 from 1.5.0 everything is broken.
The reason is that migrations from earlier versions got changed and new fields got added in these migrations.
This way, when updading from anything <v2.0.0 the database is not getting updated with the correct fields and is in an invalid state.
I have to manually change the table structure to make it work again.
Please provide a patch release that adds the migrations on top instead of changing migrations of old versions.

**Comment by mplodowski** [comment]
Please review upgrade guide. There is a patch console command.

`php artisan formbuilder:patch 2.0`

**Comment by der-On** [comment]
Thank you. Will try it and report back to you.

**Comment by der-On** [comment]
I'm sorry to say that but it is still broken. I'm on OctoberCMS build 473 wich is v1.x of October I think.
When opening the forms listing I get the following error:

```
The partial '_button_backend::lang.relation.create_name.htm' could not be found.
```

Also it seems as my custom form field templates got replaced with the default templates.

**Comment by mplodowski** [comment]
I'm sorry but the last version that support October 1.x is v1.5.0.

In upgrade guide there is following info:

**Upgrading To 2.0.1**

Plugin requires OctoberCMS version 2.x with Laravel 6.x and PHP >=7.3.

Drop support for OctoberCMS version 1.x.

**Comment by der-On** [comment]
Thank you for the information. Now I need to find out how I can pin a plugin version in OctoberCMS or prevent it from upgrading.

**Comment by mplodowski** [comment]
When you use composer you can set version like so:

`"renatio/formbuilder-plugin": "1.5.0"`

In version 1.x there should be option in the backend to freeze updates for plugin (Settings -> Updates -> Manage Plugins).

**Comment by der-On** [comment]
Thank you. Totally missed that switch, also it's so big and colorful.
