### ISSUE TITLE
Error on submit  "renderForm::onSubmit"

### ISSUE THREAD

**Issue by bojko91** [mplodowski/formbuilder-plugin-public#7]
I`ve try to add a form fields to a partial page. I'm using one of defaults forms. But when try to fill the form and hit SUBMIT button give's me this error 
"AJAX not found renderForm::onSubmit". I already add  {% framework extras %}
{% scripts %} to my Layout but still presist this error. In log manager of plugin not show up.

**To Reproduce Steps to reproduce the behavior:**
1. Add component to a partial (not to a page)

2. Go to contacts page 
3. fill up form
4. click on SUBMIT
The error: AJAX not found renderForm::onSubmit

`POST https://www.divinemobili.com/contact 500
(anonymous) @ VM8633:1
send @ jquery.min.js:2
ajax @ jquery.min.js:2
Request @ framework.js:403
$.fn.request @ framework.js:473
documentOnSubmit @ framework.js:579
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

`
**Expected behavior** To submit the form 

<a href="https://ibb.co/Db299cp"><img src="https://i.ibb.co/Db299cp/Screenshot-2021-11-30-160623.png" alt="Screenshot-2021-11-30-160623" border="0"></a> 

**October version**
 v2.1.21

**Plugin version**
v2.1.5

**Comment by bojko91** [comment]
It`s my fault. Sorry. Ypu can close this.

**Comment by sqwk** [comment]
> It`s my fault. Sorry. Ypu can close this.

What was the problem? I seem to be have the same problem.
