### ISSUE TITLE
Array to string conversion in _raw_fields_popup.htm

### ISSUE THREAD

**Issue by jameshadley** [mplodowski/formbuilder-plugin-public#8]
**Describe the bug**
```
"Array to string conversion" on line 13 of 
/html/plugins/renatio/formbuilder/controllers/forms/_raw_fields_popup.htm
```

**To Reproduce**
1. Edit any form
2. Click on the fields tab
3. Click Raw Fields Markup

**Expected behavior**
A popup appears to edit the form HTML

**Screenshots**
[View](https://www.screencast.com/t/xrts4JqsdcE)

**October version**
2.1.22

**Plugin version**
2.1.5

**Comment by mplodowski** [comment]
Hi,

please update plugin to version 2.1.6. I used PHP 7.4 syntax and that seems to be an issue in your case.

You seem to use very old PHP version. Please consider to update to at least version PHP 8.0.

https://www.php.net/supported-versions.php
